apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
  namespace: pulsewatch
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: pulsewatch
