apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: pulsewatch
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-db
          image: postgres:16
          command: ["sh","-c","until pg_isready -h postgres -U postgres; do sleep 2; done"]
      containers:
        - name: flyway
          image: pulsewatch-migrations:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef: { name: db-flyway }
          args:
            # robust retries and safe adoption of an existing DB
            - "-connectRetries=30"
            - "-baselineOnMigrate=true"
            - "migrate"
