# Ingress: allow anyone in the namespace to call the API (adjust later if needed)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-allow-namespace
  namespace: pulsewatch
spec:
  podSelector: { matchLabels: { app: api } }
  policyTypes: ["Ingress","Egress"]
  ingress:
    - from:
        - podSelector: {}   # any pod in pulsewatch
  egress:
    - to:
        - podSelector: { matchLabels: { app: postgres } }
      ports: [{ protocol: TCP, port: 5432 }]
    - to:
        - podSelector: { matchLabels: { app: redis } }
      ports: [{ protocol: TCP, port: 6379 }]
