apiVersion: v1
kind: Secret
metadata:
  name: worker-secrets
  namespace: pulsewatch
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/pulsewatch
  REDIS_URL: redis://redis:6379
