apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: worker-egress
  namespace: pulsewatch
spec:
  podSelector: { matchLabels: { app: worker } }
  policyTypes: ["Egress"]
  egress:
    # Postgres
    - to:
        - podSelector: { matchLabels: { app: postgres } }
      ports:
        - protocol: TCP
          port: 5432
    # Redis
    - to:
        - podSelector: { matchLabels: { app: redis } }
      ports:
        - protocol: TCP
          port: 6379
    # Public internet for HTTP(S) probes
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
