apiVersion: v1
kind: Service
metadata:
  name: web-lb
  namespace: pulsewatch
  annotations:
    metallb.universe.tf/address-pool: kind-pool
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80