apiVersion: v1
kind: Pod
metadata:
  name: load
  namespace: pulsewatch
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile: { type: RuntimeDefault }
  containers:
  - name: load
    image: busybox:1.36
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: { drop: ["ALL"] }
    command: ["/bin/sh","-c"]
    args:
      - while true; do wget -q -O- http://web; sleep 0.05; done