apiVersion: v1
kind: ConfigMap
metadata:
  name: flyway-migrations
  namespace: pulsewatch
data:
{{- range $filename, $content := .Values.migrations }}
  {{ $filename | quote }}: |-
{{ $content | indent 4 }}
{{- end }}