apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flyway-egress
  namespace: pulsewatch
spec:
  podSelector:
    matchLabels:
      job-name: flyway-migrate
  policyTypes: ["Egress"]
  egress:
    # Allow DNS resolution (critical!)
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    # Allow PostgreSQL connection
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 5432