manageNamespace: false
replicaCount: 1

image:
  repository: redis
  tag: "7-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379
  targetPort: 6379

networkPolicy:
  enabled: true
  allowNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: pulsewatch

resources: {}
